spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:./poll.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
      cache:
        period: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.community.dialect.SQLiteDialect}
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          web: DEBUG
          jdbc:
            datasource:
              init: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
  sql:
    init:
      mode: always
      continue-on-error: true
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET:zPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(}
  expiration: ${JWT_EXPIRATION:3600000}
  refreshExpiration: ${JWT_REFRESHEXPIRATION:604800000}